stages:
  - deploy

deploy_job:
  stage: deploy
  variables:
    RAILS_ENV: production
  before_script:
    - cd /opt/singinghill
    - git pull
    - docker pull jiting/rails-base:builder-latest
    - docker pull jiting/rails-base:production-latest
  script:
    - cd /opt/singinghill
    - docker-compose build
    - docker-compose up -d
    - docker exec singinghill_web rake clear_cache
  environment:
    name: production
    url: https://singinghill.revth.com/
  when: manual
