require: standard

inherit_gem:
  standard:
    - config/ruby-3.1.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.0

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned

Lint/MissingSuper:
  Enabled: false
